---
title: De Scratch-rugzak gebruiken
hero_image: images/banner.png
description: Leer hoe je jouw Scratch-rugzak gebruikt
version: 4
listed: false
copyedit: false
last_tested: "2020-11-26"
steps:
  - title: Inleiding
