---
title: Scratch Backpack ని ఉపయోగించడం
hero_image: images/banner.png
description: మీ Scratch backpack ని ఎలా ఉపయోగించాలో తెలుసుకోండి
version: 4
listed: false
copyedit: false
last_tested: "2020-11-26"
steps:
  - 
    title: పరిచయం
