---
title: Verwenden des Lagers in Scratch
hero_image: images/banner.png
description: Erfahre, wie du dein Scratch-Lager verwendest
version: 4
listed: false
copyedit: false
last_tested: "2020-11-26"
steps:
  - title: Einleitung
