---
title: Usando a mochila Scratch
hero_image: images/banner.png
description: Aprenda a usar sua mochila Scratch
version: 4
listed: false
copyedit: false
last_tested: "2020-11-26"
steps:
  - title: Introdução
