---
title: Uso de la mochila de Scratch
hero_image: images/banner.png
description: Aprende a usar la mochila de Scratch
version: 4
listed: false
copyedit: false
last_tested: "2020-11-26"
steps:
  - title: Introducción
