---
title: Korzystanie z plecaka w Scratch
hero_image: images/banner.png
description: Dowiedz się, jak korzystać z plecaka w Scratch
version: 4
listed: false
copyedit: false
last_tested: "2020-11-26"
steps:
  - title: Wprowadzenie
