---
title: Utiliser le sac à dos Scratch
hero_image: images/banner.png
description: Apprendre à utiliser ton sac à dos Scratch
version: 4
listed: false
copyedit: false
last_tested: "2020-11-26"
steps:
  - title: Introduction
