---
title: Utilizzare la valigetta di Scratch
hero_image: images/banner.png
description: Scopri come utilizzare la valigetta di Scratch
version: 4
listed: false
copyedit: false
last_tested: "2020-11-26"
steps:
  - title: Introduzione
